---
APPLY_FIXES: all

PRE_COMMANDS:
  - command: pip install bibtexparser
    venv: pylint # Will be run within pylint python virtualenv

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
