---
APPLY_FIXES: all

PRE_COMMANDS:
  - command: "pip install bibtexparser"
    cwd: "workspace" # Will be run at the root of the workspace

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT

ADDITIONAL_EXCLUDED_DIRECTORIES:
  - "**/.mypy_cache"