---
name: Process BibTeX Workflow

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process_bibtex:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bibtex_tools
          environment-file: environment.yml
          auto-activate-base: false

      - name: List files and check Python version
        shell: bash -l {0}
        run: |
          ls -al
          python -c 'import sys; print(sys.version_info[:])'

      - name: Download ISASPublikationen.bib
        run: |
          curl -O https://raw.githubusercontent.com/KIT-ISAS/ISAS-Publications/master/ISASPublikationen.bib

      - name: Run bibtex_to_table.py
        shell: bash -l {0}
        run: |
          python bibtex_to_table.py ISASPublikationen.bib test_output_table.table

      - name: Run generate_publication_counts_table.py
        shell: bash -l {0}
        run: |
          python generate_publication_counts_table.py ISASPublikationen.bib 1> test_output_counts.xml

      - name: Check output files
        run: |
          test_output_counts_size=$(stat -c%s "test_output_counts.xml")
          test_output_table_size=$(stat -c%s "test_output_table.table")
          isas_publikationen_size=$(stat -c%s "ISASPublikationen.bib")

          if [ ! -s "test_output_table.table" ] || [ ! -s "test_output_counts.xml" ]; then
            echo "Error: Output files are empty."
            exit 1
          fi

          if [ "$test_output_counts_size" -lt 1024 ]; then
            echo "Error: test_output_counts.xml is less than 1 kilobyte."
            exit 1
          fi

          half_isas_publikationen_size=$((isas_publikationen_size / 2))
          if [ "$test_output_table_size" -lt "$half_isas_publikationen_size" ]; then
            echo "Error: test_output_table.table is less than half the size of ISASPublikationen.bib."
            exit 1
          fi
